// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhotoLibBackendClean.Models;

#nullable disable

namespace PhotoLibBackendClean.Migrations
{
    [DbContext(typeof(PhotoContext))]
    [Migration("20250613162944_LatitudeLongitudeRemove")]
    partial class LatitudeLongitudeRemove
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PhotoLibBackendClean.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ExifData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Photos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Гэта тэставае апісанне",
                            ExifData = "EXIF: ISO 100, f/2.8",
                            Title = "Тэставае фота",
                            Url = "https://example.com/photo1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Апісанне другога фота",
                            ExifData = "EXIF: ISO 200, f/5.6",
                            Title = "Другое фота",
                            Url = "https://example.com/photo2.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
